version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: ledgermesh-zipkin
    ports:
      - "9411:9411"
    networks:
      - ledgermesh-net
  postgres:
    image: postgres:16
    container_name: ledgermesh-postgres
    environment:
      POSTGRES_USER: ledgermesh
      POSTGRES_PASSWORD: ledgermesh
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledgermesh"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ledgermesh-net
  redis:
    image: redis:7
    container_name: ledgermesh-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ledgermesh-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: ledgermesh-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ledgermesh-net
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: ledgermesh-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - ledgermesh-net
volumes:
  pgdata:

networks:
  ledgermesh-net:
    driver : bridge