spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=account-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/accounts/**

spring.cloud.gateway.server.webmvc.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.id=accountServiceCB
spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.fallbackUri=forward:/fallback/accounts

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[1].filters[0].args.id=authServiceCB
spring.cloud.gateway.server.webmvc.routes[1].filters[0].args.fallbackUri=forward:/fallback/auth

spring.cloud.gateway.server.webmvc.routes[2].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/transactions/**

spring.cloud.gateway.server.webmvc.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[2].filters[0].args.id=transactionServiceCB
spring.cloud.gateway.server.webmvc.routes[2].filters[0].args.fallbackUri=forward:/fallback/transactions

spring.cloud.gateway.server.webmvc.routes[3].id=budget-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://BUDGET-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/budgets/**

spring.cloud.gateway.server.webmvc.routes[3].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[3].filters[0].args.id=budgetServiceCB
spring.cloud.gateway.server.webmvc.routes[3].filters[0].args.fallbackUri=forward:/fallback/budgets

spring.cloud.gateway.server.webmvc.routes[4].id=notification-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.server.webmvc.routes[4].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[4].filters[0].args.id=notificationServiceCB
spring.cloud.gateway.server.webmvc.routes[4].filters[0].args.fallbackUri=forward:/fallback/notifications

management.endpoints.web.exposure.include=gateway,health,info
logging.level.org.springframework.security=DEBUG

resilience4j.circuitbreaker.instances.accountServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.accountServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.accountServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.accountServiceCB.minimum-number-of-calls=3

resilience4j.circuitbreaker.instances.authServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.authServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.authServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.authServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.authServiceCB.minimum-number-of-calls=3

resilience4j.circuitbreaker.instances.transactionServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.transactionServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.transactionServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.transactionServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.transactionServiceCB.minimum-number-of-calls=3

resilience4j.circuitbreaker.instances.budgetServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.budgetServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.budgetServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.budgetServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.budgetServiceCB.minimum-number-of-calls=3

resilience4j.circuitbreaker.instances.notificationServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.notificationServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.notificationServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.notificationServiceCB.minimum-number-of-calls=3