spring.application.name=account-service
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:accountdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.cloud.config.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/